### ISSUE TITLE
Update to 0.2.0 fails

### ISSUE THREAD

**Issue by mhzawadi** [tadhglewis/issue-status#336]
Hello,

have just got round to updating my install and it fails

Config:
```json
{
  "name": "issue-status",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "issue-status dev",
    "build": "issue-status build",
    "preview": "issue-status preview"
  },
  "dependencies": {
    "issue-status": "^0.2.0"
  },
  "packageManager": "pnpm@10.12.1"
}
```

the error
```shell
± |main ✓| → pnpm run build

> issue-status@ build /Users/matt/git/issue-status
> issue-status build

failed to load config from /Users/matt/git/issue-status/node_modules/.pnpm/issue-status@0.2.0_@types+react@19.1.8_jiti@2.6.0_lightningcss@1.30.1/node_modules/issue-status/vite.config.ts
node:internal/modules/package_json_reader:255
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
        ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'tsx' imported from /Users/matt/git/issue-status/node_modules/.pnpm/issue-status@0.2.0_@types+react@19.1.8_jiti@2.6.0_lightningcss@1.30.1/node_modules/issue-status/node_modules/.vite-temp/vite.config.ts.timestamp-1759258945555-11dd207bc0b268.mjs
    at Object.getPackageJSONURL (node:internal/modules/package_json_reader:255:9)
    at packageResolve (node:internal/modules/esm/resolve:767:81)
    at moduleResolve (node:internal/modules/esm/resolve:853:18)
    at defaultResolve (node:internal/modules/esm/resolve:983:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:801:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:725:25)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:708:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:309:38)
    at #link (node:internal/modules/esm/module_job:202:49) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v24.3.0
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by tadhglewis** [comment]
@mhzawadi this should be fixed in `0.2.1`. it's very possible you'll need to update your [index.html style overrides](https://github.com/mhzawadi/issue-status/blob/main/index.html#L10-L11) as the index.css is hashed and may have changed.

I'm keen to explore how to natively support your style use case without implementing those hacks though

**Comment by mhzawadi** [comment]
Thanks, but I have bad news. The build still fails, if you have a process I can follow that would be amazing.

1. update `package.json` with new version
2. run `pnpm update`
3. run `pnpm build`

get error

```shell
± |main ✓| → pnpm build

> issue-status@ build /Users/matt/git/issue-status
> issue-status build

failed to load config from /Users/matt/git/issue-status/node_modules/.pnpm/issue-status@0.2.1_@types+react@19.2.2_jiti@2.6.1_lightningcss@1.30.1/node_modules/issue-status/vite.config.ts

node:internal/modules/run_main:105
    triggerUncaughtException(
    ^
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/matt/git/issue-status/node_modules/.pnpm/dayjs@1.11.13/node_modules/dayjs/esm/constant' imported from /Users/matt/git/issue-status/node_modules/.pnpm/dayjs@1.11.13/node_modules/dayjs/esm/index.js
    at finalizeResolution (node:internal/modules/esm/resolve:274:11)
    at moduleResolve (node:internal/modules/esm/resolve:859:10)
    at defaultResolve (node:internal/modules/esm/resolve:983:11)
    at nextResolve (node:internal/modules/esm/hooks:748:28)
    at o (file:///Users/matt/git/issue-status/node_modules/.pnpm/@tailwindcss+node@4.1.14/node_modules/@tailwindcss/node/dist/esm-cache.loader.mjs:1:69)
    at nextResolve (node:internal/modules/esm/hooks:748:28)
    at resolve (file:///Users/matt/git/issue-status/node_modules/.pnpm/tsx@4.20.6/node_modules/tsx/dist/esm/index.mjs?1759993323283:2:5279)
    at nextResolve (node:internal/modules/esm/hooks:748:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:240:30)
    at handleMessage (node:internal/modules/esm/worker:199:24) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///Users/matt/git/issue-status/node_modules/.pnpm/dayjs@1.11.13/node_modules/dayjs/esm/constant'
}

Node.js v24.4.1
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by tadhglewis** [comment]
@mhzawadi hmm I'm not able to reproduce your error locally, even with your repo cloned down. I can also see https://github.com/mhzawadi/issue-status/commit/15c80972f38de2a5f33236c76c54875d525690e3 is passing build successfully?

I can see [your site](https://status.horwood.biz/) is running 0.2.1 with translations - although missing CSS due to the hash as previously mentioned

**Comment by mhzawadi** [comment]
well thats very odd, I have deleted the repo, cleared out all cache files I can find.

re-cloaned the repo, `pnpm install`, then `pnpm build` and it fails with the same issue.

This could be a node version issue or maybe an arm issue.

Going to park it for now. Thanks for your help

**Comment by mhzawadi** [comment]
FYI: the build is failing on node24, works fine on node20
